# Generated by Django 4.0.5 on 2022-06-27 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Date of transaction'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='detail',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_ty', models.CharField(choices=[('SL', 'Salary'), ('CO', 'Commission'), ('IN', 'Interest'), ('SA', 'Sales'), ('IV', 'Investments'), ('GF', 'Gifts'), ('AL', 'Allowances')], default='SL', max_length=2)),
                ('income_detail', models.TextField(blank=True, max_length=500)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(null=True, verbose_name='Date of transaction')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
    ]
