# Generated by Django 4.0.5 on 2022-07-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
